[window]
dimensions = { columns = 100, lines = 30 }
position = { x = 20, y = 15 }
padding = { x = 1, y = 0 }
#No funcionan en X11
#opacity = 0.60
#blur = true

[font]
size = 11

[cursor]
style = { shape = "Beam", blinking = "On" }
